### PR TITLE
WIP : Python 2/3 compatibility

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This should allow atom to work both on python 2 and 3. It needs more tests. I can compile and import atom.api under both python 2 and python 3 (tested under linux, under windows (anaconda+mingw) I cannot get python 3 to import, it segfaults).
I added the future package as a dependency to smooth the use of metaclasses.

Comments are welcome.
While testing I will try to improve the testsuite. I may not have much time to work on this this week but I will keep you posted.

### CODE REVIEW

**Comment by peterazmanov** [comment]
Sorry for the delay, I'll merge it as soon as I can (in worst case by the end of the week).

**Comment by MatthieuDartiailh** [comment]
Doing some testing of your own first might make sense. I have not tested everything yet. Once you merge I will start working on enaml so that I can test my application on Python 2 and 3.

**Comment by peterazmanov** [comment]
I looked through your changes, they seem right to me. I didn't have time to test your pull request during this week (the amount of work on byteplay exceeded my expectations). I'll test new version of Atom with my application on Python 3, and merge it  after I finish testing byteplay. Hope it'll happen on Monday or Tuesday.

**Comment by MatthieuDartiailh** [comment]
Sounds good

**Comment by MatthieuDartiailh** [comment]
Great !
Would you welcome a similar PR for Enaml ?

**Comment by peterazmanov** [comment]
I added several commits atop of merged PR. I fixed some inconsistencies in tabs/spaces and removed one usage of IS_PY3K macro for which I couldn't find definition. There are several usages of this macro in atom-1.0.0-dev but no definition either...

> Would you welcome a similar PR for Enaml ?

Any changes that would improve code will be appreciated )

**Comment by MatthieuDartiailh** [comment]
I am sorry I had no time to test my latest commit (for python 3.5). I will give a look at your changes before starting any work on enaml.

**Pull request merged**
